// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8pqDmbG7nhb_xTAYu0oBhxVubf-VkTkU',
    appId: '1:962133212140:android:0ff99f21ee270f58f71ec9',
    messagingSenderId: '962133212140',
    projectId: 'addtocart-ee062',
    storageBucket: 'addtocart-ee062.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPio9Q71ieBe6TytieSGH_Vo6giCr-iYA',
    appId: '1:962133212140:ios:47fafef1323c2dd3f71ec9',
    messagingSenderId: '962133212140',
    projectId: 'addtocart-ee062',
    storageBucket: 'addtocart-ee062.firebasestorage.app',
    iosBundleId: 'com.example.isarChateapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPio9Q71ieBe6TytieSGH_Vo6giCr-iYA',
    appId: '1:962133212140:ios:47fafef1323c2dd3f71ec9',
    messagingSenderId: '962133212140',
    projectId: 'addtocart-ee062',
    storageBucket: 'addtocart-ee062.firebasestorage.app',
    iosBundleId: 'com.example.isarChateapp',
  );
}
